UTDNebula/planner

- README.md
I updated some of the contents on the ReadMe.
> Medhaaiyah patch 1 1

- src/courses/actions.ts
- src/planner/SchedulePlanner.tsx
- Add a missing referenced `actions.ts` file that was left out of #15.
> Fix module errors in SchedulePlanner

- src/planner/reducers.ts
- src/schedules/actions.ts
- Add a missing referenced `actions.ts` file that was left out of #16.
> Fix missing files in SchedulePlanner

- src/schedules/ScheduleList.tsx
- src/schedules/ScheduleListPage.tsx
- Add missing referenced `ScheduleList.tsx` and `ScheduleListPage.tsx` files that were left out of #17, #16, and #15 
If I have still left out files, please kick me off the team. /s
> Fix missing ScheduleListPage components

- .editorconfig
- .eslintignore
- .eslintrc.js
- .prettierrc.js
- package-lock.json
- package.json
This PR adds ESLint and associated plugins like [Prettier](https://prettier.io/) to format code and enforce a common code style for contributors.
This updates the `package.json` config to automatically run ESLint and fix code on commits.
> style: Add linter and code style fixes

- package-lock.json
- package.json
- src/courses/CourseCard.tsx
- src/planner/CourseSourceSidebar.tsx
- src/planner/SchedulePlanner.tsx
- src/planner/SchedulePlannerStyle.tsx
- src/planner/SemesterBlock.tsx
- src/styling.ts
Added a 'styling.ts' file containing all the styling for components.
Converted some styled divs into material-ui components.
> Migrate components to Material-UI

- package-lock.json
- package.json
- src/App.tsx
- src/courses/CourseCard.tsx
- src/dummy_schedule.json
- src/landing/index.css
- src/landing/index.tsx
- src/planner/SchedulePlannerStyle.tsx
- src/planner/SemesterBlock.tsx
- src/styling.ts
Created the official landing page and added some styling to the drag and drop interface.
Issues:
1. The a tag on the bottom bar with the text "BUILT BY THE ASSOCIATION FOR COMPUTING MACHINERY AT UTD" is underlined in blue and I'm not sure how to fix this. I tried textDecoration: 'none', but that did not work.
2. The buttons are not linked to their respective components because I was not sure where or how to link them.
> feat: Create landing page

- package-lock.json
- package.json
- src/auth0-config.js
- src/index.tsx
- src/landing/index.tsx
- src/users/UserAuth.tsx
- tsconfig.json
Implemented ACM’s Auth0 to get started on the sign-in workflow. The button on the landing page dynamically changes to sign-in / sign-out based on the user's authentication state
> chore: Implement auth front-end using Sign-in with ACM

- README.md
- components/common/Footer.tsx
Resolves #99 
The text in the footer that said "Built with ❤️ and 💻 by ACM Development" was changed to "Built with ❤️ and 💻 by Project Nebula Maintainers"
> Change authors attribution in site footer

- README.md
- components/common/Footer.tsx
"semeester" on line 25 changed to "semester"
"Generate" on line 27 changed to "Generating"
> Fix typos in the README

- pages/_document.tsx
- styles/globals.css
- tailwind.config.js
Added colors & fonts from Planner style guide
Resolves #127
> refactor: Add custom color palette and fonts

- CODEOWNERS
- README.md
> Update README.md & CODEOWNERS

- NEW_CONTRIBUTORS.md
Created NEW_CONTRIBUTORS.md to teach new Recruits how to use the Git workflow
> chore: Add file for engineering workflow

- src/pages/_app.tsx
FIxed the issue for wrong page invocation with the planner icon images
> fixed planner@16px error

- src/pages/auth/login.tsx
Resolves #350 
Deleted the email provider from provider objects.
Added `@ts-ignore` because the keys were not optional and copying providers into new object and filtering on values required importing next-auth types for creating the object
Let me know if that is how you would like it to be done.
> deleted email provider

- next.config.js
Removing console logs from production build.
> next config updated to remove console logs

- .gitpod.yml
- package.json
> chore: use correct auth url for gitpod

- .eslintrc.js
- package-lock.json
- package.json
> Add react-hooks to eslint

- public/index.html
Fixes an issue where page did not appear responsive due to incorrect scaling on mobile devices
> Fix scaling issue on mobile

- public/index.html
List the GitHub issues containing the issues relevant to this pull request.
[For example, "Resolves #1, closes #2, fixes #3", etc.]
Describe your changes here at a high level, describing how this PR fits into the
rest of the project.
Go more into detail about key files that were modified and why they were
updated. Do not list every file that was modified; only note the ones most
relevant to this feature or bug fix.
If were roadblocks encountered during development that remain unresolved or any
future additions or changes to make, note them here. Otherwise. Feel free to
delete this section if it isn't needed.
> Made changes to landing page

- public/index.css
- public/index.html
List the GitHub issues containing the issues relevant to this pull request.
[For example, "Resolves #1, closes #2, fixes #3", etc.]
Describe your changes here at a high level, describing how this PR fits into the
rest of the project.
Go more into detail about key files that were modified and why they were
updated. Do not list every file that was modified; only note the ones most
relevant to this feature or bug fix.
If were roadblocks encountered during development that remain unresolved or any
future additions or changes to make, note them here. Otherwise. Feel free to
delete this section if it isn't needed.
> Made changes to index.html

- public/index.css
- public/index.html
+ Select the "design" tab of the Meet the Team section by default
+ Fix the layout of the Meet the Team section on mobile
+ Make text wrap more flexibly in intro section, especially on mobile
> Make landing page more responsive

- public/index.html
Update email address on the contact us form to planner@utdnebula.com from planner@utdallas.edu
> Update email address on landing page

- public/index.css
- public/index.html
Show all team members at once because two of the teams only have 2 members and it looks awkward. Don't really see why it has to be split up anyway, since we mention what their role is.
Compared to
> Merge team

- .github/workflows/tests.yml
- package.json
- prisma/seedTemplates.ts
- tests/prisma/seedTemplates.spec.ts
> Internal/DB Seed Test

- .github/workflows/build.yml
- .github/workflows/format.yml
- .github/workflows/tests.yml
Remove `master` and `release/*` branches from workflows.
> perf: fix workflows

- src/components/planner/SemesterContext.tsx
- src/server/trpc/router/plan.ts
- src/utils/plannerUtils.ts
- src/utils/utilFunctions.ts
- tests/util/utilFunctions.spec.ts
> refactor(NP-78): ``createNewYear`` 

- src/components/planner/CourseInfoHoverCard.tsx
- src/components/planner/Sidebar/SidebarCourseItem.tsx
- src/components/planner/Tiles/SemesterCourseItem.tsx
- src/utils/utilFunctions.ts
- tests/util/utilFunctions.spec.ts
Waiting for #594 to get merged. Please review #594 first.
> test(NP-78): Add tests for `utilsFunctions.ts`

- .github/workflows/delete-neon-branch.yml
- .github/workflows/deploy-preview.yml
List the GitHub issues containing the issues relevant to this pull request.
[For example, "Resolves #1, closes #2, fixes #3", etc.]
Describe your changes here at a high level, describing how this PR fits into the
rest of the project.
Go more into detail about key files that were modified and why they were
updated. Do not list every file that was modified; only note the ones most
relevant to this feature or bug fix.
If were roadblocks encountered during development that remain unresolved or any
future additions or changes to make, note them here. Otherwise. Feel free to
delete this section if it isn't needed.
> Use correct ref for Neon branch names

- .github/workflows/delete-neon-branch.yml
- .github/workflows/deploy-preview.yml
List the GitHub issues containing the issues relevant to this pull request.
[For example, "Resolves #1, closes #2, fixes #3", etc.]
Describe your changes here at a high level, describing how this PR fits into the
rest of the project.
Go more into detail about key files that were modified and why they were
updated. Do not list every file that was modified; only note the ones most
relevant to this feature or bug fix.
If were roadblocks encountered during development that remain unresolved or any
future additions or changes to make, note them here. Otherwise. Feel free to
delete this section if it isn't needed.
> refactor(NP-87): PR close event

- .github/workflows/deploy-preview.yml
See: https://github.com/UTDNebula/planner/pull/622#issuecomment-1657048979
> fix: add `pgbouncer` param to preview connection strings

- validator/degree_solver.py
NP-37
Only leftover courses that aren't used in core or major should be counted as free electives.
> Don't count core classes as free electives NP-37

- CODEOWNERS
See agreement in: https://nebula-labs.atlassian.net/wiki/spaces/NP/pages/34832653/08-28-23+Planner+Engineering+Meeting.
> chore: add pr-reviewers team

- package-lock.json
- package.json
- src/components/landing/PlanCard.tsx
- tailwind.config.js
Went through all the components @ https://daisyui.com/components. We were using the `dropdown` but not even correctly because it was already replaced with the Radix one.
> refactor(NP-25): remove daisyui
